# Generated by Django 4.1.7 on 2023-04-03 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0002_qualifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State_Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='qualifications',
            name='Qualifications_Name',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District_Name', models.CharField(max_length=30)),
                ('State_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tapp.state')),
            ],
        ),
    ]
