# Generated by Django 4.1.7 on 2023-04-04 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0003_state_alter_qualifications_qualifications_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=25)),
                ('Last_Name', models.CharField(max_length=25)),
                ('Date_of_Birth', models.DateField()),
                ('Guardian_Details', models.CharField(max_length=25)),
                ('Whatsapp_Number', models.IntegerField(max_length=10)),
                ('Contact_Number', models.IntegerField(max_length=10)),
                ('batchname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tapp.batch')),
            ],
        ),
    ]
